- name: Automate Server Management Tasks
  hosts: 10.112.0.11
  become: true
  vars:
    remote_log_path: "/var/log/syslog"
    local_log_path: "syslog"
    start_time: "2025-02-03 00:00:00"
    end_time: "2025-02-04 23:59:59"
    process_to_kill: "sleep"

  tasks:

    - name: Check high memory and CPU usage
      shell: "ps aux --sort=-%mem,-%cpu | head -5"
      register: high_usage

    - name: Display high memory and CPU usage
      debug:
        msg: "{{ high_usage.stdout }}"

    - name: Check disk utilization
      command: df -h
      register: disk_utilization

    - name: Display disk utilization
      debug:
        msg: "{{ disk_utilization.stdout }}"

    - name: Check if the process exists
      shell: "pgrep -f {{ process_to_kill }}"
      register: process_exists
      ignore_errors: yes

    - name: Display message if process doesn't exist
      debug:
        msg: "The process '{{ process_to_kill }}' doesn't exist. Continuing with the next tasks."
      when: process_exists.rc != 0

    - name: Kill the process if it exists
      shell: "pkill -f {{ process_to_kill }}"
      when: process_exists.rc == 0

    - name: Confirm process has been handled
      debug:
        msg: "Process handling completed. Moving on to the next task."
