---
- name: Detect and Report Inactive Azure AD Users
  hosts: localhost
  gather_facts: no
  vars:
    AZURE_TENANT_ID: "{{ azure_tenant_id }}"
    AZURE_CLIENT_ID: "{{ azure_client_id }}"
    AZURE_CLIENT_SECRET: "{{ azure_client_secret }}"
    days_inactive: 10
    output_file: "/tmp/azure_ad_inactive_users.json"

  tasks:
    - name: Get Azure AD Access Token
      uri:
        url: "https://login.microsoftonline.com/{{ AZURE_TENANT_ID }}/oauth2/v2.0/token"
        method: POST
        body: "client_id={{ AZURE_CLIENT_ID }}&scope=https://graph.microsoft.com/.default&client_secret={{ AZURE_CLIENT_SECRET }}&grant_type=client_credentials"
        headers:
          Content-Type: "application/x-www-form-urlencoded"
        return_content: yes
      register: auth_response

    - name: Set access token
      set_fact:
        access_token: "{{ auth_response.json.access_token }}"

    - name: Get all users with sign-in activity from Azure AD (Beta endpoint)
      uri:
        url: "https://graph.microsoft.com/beta/users?$select=displayName,userPrincipalName,signInActivity"
        method: GET
        headers:
          Authorization: "Bearer {{ access_token }}"
        return_content: yes
      register: users_response

    - name: Filter inactive users based on lastSignInDateTime
      set_fact:
        inactive_users: >-
          {{
            users_response.json.value | selectattr('signInActivity.lastSignInDateTime', 'defined') | selectattr(
              'signInActivity.lastSignInDateTime',
              'search',
              '^((?![0-9]{4}-[0-9]{2}-[0-9]{2}).)*$'
            ) | list
          }}

    - name: Save results to JSON
      copy:
        dest: "{{ output_file }}"
        content: "{{ inactive_users | to_nice_json }}"
