- name: Fetch Entire Confluence Repository
  hosts: localhost
  gather_facts: no
  vars:
    confluence_url: "https://surajg18102002.atlassian.net/wiki"
    confluence_token: "c3VyYWpnMTgxMDIwMDJAZ21haWwuY29tOkFUQVRUM3hGZkdGMGxLM0ItRzNXUXVTZF9FeVVud29qTFFkNXVvUG5lVmJnLWlYWlM0NXBIUm9fcDNVZ2RSQXdKWF95ZkxZV1FfUUFjdEZpY3VTel9jMWt2ODVTQjhXaUFQVktQcmVRMElRUWhnbTV5Mkt2bGlTQTdWZV9YR1dpVUx6NTlMSE9SekRCczcwOUFTRUcxc2VLVXA5a1JDXzdTZ3Z4VDAxR3p3NFp4SFZHZWUxOTZEUT1GNzM3NDMwOQ=="  
    output_dir: "/tmp/confluence_repository"  # Directory to save extracted documents

  tasks:
    - name: Ensure output directory exists
      ansible.builtin.file:
        path: "{{ output_dir }}"
        state: directory
        mode: '0755'

    - name: Fetch all Confluence spaces
      ansible.builtin.uri:
        url: "{{ confluence_url }}/rest/api/space?limit=100"
        method: GET
        headers:
          Authorization: "Bearer {{ confluence_token }}"
          Accept: "application/json"
        return_content: yes
      register: spaces_response

    - name: Extract space keys
      set_fact:
        space_keys: "{{ spaces_response.json.results | map(attribute='key') | list }}"

    - name: Fetch all pages from each space
      ansible.builtin.uri:
        url: "{{ confluence_url }}/rest/api/content?type=page&spaceKey={{ item }}&limit=100&expand=body.storage"
        method: GET
        headers:
          Authorization: "Bearer {{ confluence_token }}"
          Accept: "application/json"
        return_content: yes
      loop: "{{ space_keys }}"
      register: pages_responses

    - name: Save extracted pages to files
      ansible.builtin.copy:
        content: "{{ item.json }}"
        dest: "{{ output_dir }}/confluence_space_{{ item.item }}.json"
      loop: "{{ pages_responses.results }}"

    - name: Display summary of extracted content
      ansible.builtin.debug:
        msg: "Extracted Confluence spaces: {{ space_keys | length }} and saved pages to {{ output_dir }}"
