- name: Fetch Document from Confluence
  hosts: localhost
  gather_facts: no
  vars:
    confluence_url: "https://surajg18102002.atlassian.net/wiki"
    confluence_token: "c3VyYWpnMTgxMDIwMDJAZ21haWwuY29tOkFUQVRUM3hGZkdGMGxLM0ItRzNXUXVTZF9FeVVud29qTFFkNXVvUG5lVmJnLWlYWlM0NXBIUm9fcDNVZ2RSQXdKWF95ZkxZV1FfUUFjdEZpY3VTel9jMWt2ODVTQjhXaUFQVktQcmVRMElRUWhnbTV5Mkt2bGlTQTdWZV9YR1dpVUx6NTlMSE9SekRCczcwOUFTRUcxc2VLVXA5a1JDXzdTZ3Z4VDAxR3p3NFp4SFZHZWUxOTZEUT1GNzM3NDMwOQ=="
    confluence_page_id: "98309"  # Extracted from your URL

  tasks:
    - name: Fetch document from Confluence
      ansible.builtin.uri:
        url: "{{ confluence_url }}/rest/api/content/{{ confluence_page_id }}?expand=body.storage"
        method: GET
        headers:
          Authorization: "{{ confluence_token }}"
          Accept: "application/json"
        return_content: yes
      register: confluence_doc

    - name: Save fetched Confluence document
      ansible.builtin.copy:
        content: "{{ confluence_doc.content }}"
        dest: "/tmp/confluence_document_{{ confluence_page_id }}.json"

    - name: Display fetched Confluence data
      ansible.builtin.debug:
        msg: "{{ confluence_doc.json }}"
