---
- name: Manage Linux Server Tasks
  hosts: 10.112.0.11
  become: true
  vars:
    remote_log_path: "{{remote_log_path}}"
    local_log_path: "{{local_log_path}}"
    start_time: "{{start_time}}"
    end_time: "{{end_time}}"

  tasks:
    - name: Fetch files from server
      fetch:
        src: "{{ remote_log_path }}"
        dest: "./fetched_logs/"
        flat: yes

    - name: Scrap log file for specific duration
      shell: "awk '$0 ~ /{{ start_time }}/,/{{ end_time }}/' {{ remote_log_path }}"
      register: log_output

    - name: Save log output locally
      copy:
        content: "{{ log_output.stdout }}"
        dest: "./retrieved_logs.txt"
        
    - name: Display scraped logs
      debug:
        msg: "{{ log_output.stdout_lines }}"
        
    - name: Check for high memory and CPU usage processes
      shell: "ps aux --sort=-%mem,-%cpu | head -5"
      register: process_output

    - name: Display high resource-consuming processes
      debug:
        msg: "{{ process_output.stdout_lines }}"

    - name: Check disk utilization
      command: df -h
      register: disk_usage

    - name: Display disk usage
      debug:
        msg: "{{ disk_usage.stdout_lines }}"
