---
- name: Check CPU Usage and Identify All Processes
  hosts: 20.55.88.203
  become: yes
  tasks:
    - name: Gather system performance facts
      ansible.builtin.setup:
        gather_subset:
          - hardware
      register: system_info

    - name: Show CPU usage
      debug:
        msg: "Current CPU Usage: {{ system_info.ansible_facts.ansible_processor_vcpus }} cores"

    - name: Get process details
      ansible.builtin.command: "ps -eo pid,comm,%cpu --sort=-%cpu --no-headers"
      register: process_info

    - name: Convert process details to JSON
      set_fact:
        processes: "{{ process_info.stdout_lines | map('split', ' ') | list | map('regex_replace', '^(\\d+)\\s+(\\S+)\\s+([\\d\\.]+)$', '{\"pid\": \"\\1\", \"command\": \"\\2\", \"cpu\": \"\\3\"}') | list }}"

    - name: Show all processes in JSON format
      debug:
        msg: "{{ processes }}"
