- name: Automate Server Management Tasks
  hosts: 10.112.0.11
  become: true
  vars:
    remote_log_path: "{{remote_log_path}}"
    local_log_path: "{{local_log_path}}"
    retrieved_log_path: "retrieved_logs.txt"
    start_time: "{{start_time}}"
    end_time: "{{end_time}}"

  tasks:
    - name: Fetch log file from remote server
      fetch:
        src: "{{ remote_log_path }}"
        dest: "{{ local_log_path }}"
        flat: yes

    - name: Scrape logs between specific timestamps
      shell: |
        sed -n '/{{ start_time }}/,/{{ end_time }}/p' {{ local_log_path }}/{{ remote_log_path | basename }}
      register: scraped_logs

    - name: Display scraped logs
      debug:
        msg: "{{ scraped_logs.stdout_lines }}"

    - name: Check high memory and CPU usage
      shell: "ps aux --sort=-%mem,-%cpu | head -5"
      register: high_usage

    - name: Display high memory and CPU usage
      debug:
        msg: "{{ high_usage.stdout }}"

    - name: Check disk utilization
      command: df -h
      register: disk_utilization

    - name: Display disk utilization
      debug:
        msg: "{{ disk_utilization.stdout }}"

